Repository soham4abc/CP_repository, pull requests merged in 2022-10, with the labels that each got.

#6 Abhishek tiwari added readme
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#5 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#7 Readme urls updated
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#11 gfg prob for queries of a matrix
  Queries_on_a_Matrix/Queries_on_a_Matrix.cpp
  Queries_on_a_Matrix/Queries_on_a_Matrix.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#12 Singlelinkedlist
  old_programs/single_linked_list.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#10 gfg prob to solve bst to dll prob
  Binary_Tree_to_DLL/Binary_Tree_to_DLL.cpp
  Binary_Tree_to_DLL/Binary_Tree_to_DLL.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#13 Create Bitwise Operators in C folder
  Bitwise Operators in C/bitwise_oparators.c
  Bitwise Operators in C/bitwise_operators.md
  Digit Frequency/digit_frequency.c
  Digit Frequency/digit_frequency.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#14 Make the digit_frequency.md correct
  Digit Frequency/digit_frequency.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#16 let's echo
  lets_echo/README.md
  lets_echo/echo.sh
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#15 readme-fix
  Binary_Tree_to_DLL/README.md
  Bitwise Operators in C/README.md
  Digit Frequency/README.md
  Kadane's_Algorithm/README.md
  Queries_on_a_Matrix/README.md
  min_no_of_jumps/README.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#17 Make Boxes through a Tunnel
  Boxes through a Tunnel/boxes_through_a_tunnel.c
  Boxes through a Tunnel/boxes_through_a_tunnel.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#18 documentation fix
  Boxes through a Tunnel/README.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#19 loop in python, while loop
  loop_in_python/README.md
  loop_in_python/while_loop.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#20 SQL query Demo
  where_in_sql/README.md
  where_in_sql/city.sql
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#21 Make Printing Tokens
  Printing Tokens/README.md
  Printing Tokens/printing_tokens.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#22 formatted_payment in java
  java_formatted_payment/README.md
  java_formatted_payment/formatted_payment.jar
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#24 added python problem for basic if else function
  ifelseinpython/README.md
  ifelseinpython/ifelseinpython.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#26 Created DiceCombination File
  DiceCombinations/DiceCombinations.cpp
  DiceCombinations/readme.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#28 quicksort using cpp
  QuickSort alogorithm/Quicksort.cpp
  QuickSort alogorithm/Readme.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#27 added cpp program for addition of multiple numbers
  addincpp/README.md
  addincpp/addincpp.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#30 added shell script to perform basic arithmatic operations
  arithmaticinshell/README.md
  arithmaticinshell/basicshelloperations.sh
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#25 Create DNF.cpp
  Dutch National Flag Algorithm/DNF.cpp
  Dutch National Flag Algorithm/README.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#32 Added new CP Meme-Man
  MemeMan/description.md
  MemeMan/meme_man.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#33 added k smallest
  K_Smallest/README.md
  K_Smallest/k_smallest.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#36 added file of MinimizingCoins.cpp, insteresting problem of dp
  MinimizingCoins/MinimisingCoins.cpp
  MinimizingCoins/readme.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#37 Added Combination based CP problems
  DiceCombinations/DiceCombinations.cpp
  Digit Frequency/digit_frequency.c
  K_Smallest/k_smallest.cpp
  java_formatted_payment/formatted_payment.jar
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#38 Added a problem Filling Bucket (DP problem)
  Filling Bucket/README.md
  Filling Bucket/fillingBucket.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#39 added valid sudoku problem
  ValidSudoku/README.md
  ValidSudoku/ValidSudoku.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#41 Sum and Difference
  SumAndDifference/Program.c
  SumAndDifference/Readme.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022
